export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  PROGRAM_MANAGER: "PROGRAM_MANAGER",
  DOMAIN_MANAGER: "DOMAIN_MANAGER",
  TASK_REVIEWER: "TASK_REVIEWER",
  COMMUNITY_MANAGER: "COMMUNITY_MANAGER",
  STORE_MANAGER: "STORE_MANAGER",
  FINANCE_MANAGER: "FINANCE_MANAGER",
  AMBASSADOR: "AMBASSADOR"
} as const;

export type RoleKey = (typeof ROLES)[keyof typeof ROLES];
